plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'br.org.eldorado.hiaac.aidl.hiaacaidlcontract'
    compileSdk 34

    defaultConfig {
        minSdk 29
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = project.group
                artifactId = 'hiaacaidlcontract'
                version = project.version
            }
        }
    }
}


